# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install landbosse
  - pip install pandas==0.25.2
  - pip install numpy
  - pip install sympy
  - pip install shapely
  - pip install xlsxwriter
  - pip install xlrd
  - pip install psycopg2-binary
  - pip install sqlalchemy
  - pip install pytest


env:
  global:
    - LANDBOSSE_INPUT_DIR: $TRAVIS_BUILD_DIR/project_input_template
    - LANDBOSSE_OUTPUT_DIR: $TRAVIS_BUILD_DIR/project_input_template

# Command to run tests, e.g. python setup.py test
script:
  - python $TRAVIS_BUILD_DIR/LandBOSSE/main.py --validate

branches:
  only:
    - develop
